import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { 
  ArrowLeft, 
  Smartphone, 
  ShieldCheck, 
  AlertTriangle,
  CheckCircle2
} from "lucide-react";

const TwoFactorAuth = () => {
  const navigate = useNavigate();
  const [step, setStep] = useState(1); // 1: Info, 2: Setup, 3: Success

  const handleNext = () => {
    if (step < 2) setStep(step + 1);
    else if (step === 2) {
      setStep(3);
    }
  };

  return (
    <div className="min-h-screen bg-background pb-32">
      <div className="sticky top-0 z-30 border-b border-border bg-background/80 backdrop-blur-md">
        <div className="mx-auto flex max-w-xl items-center gap-3 px-4 py-4 sm:px-6">
          <button 
            onClick={() => navigate("/settings")}
            className="rounded-full p-2 text-muted-foreground hover:bg-secondary hover:text-foreground transition-colors"
          >
            <ArrowLeft className="h-5 w-5" />
          </button>
          <h1 className="text-xl font-bold text-foreground">Two-Factor Authentication</h1>
        </div>
      </div>

      <div className="mx-auto max-w-xl px-4 py-8 sm:px-6">
        {step === 1 && (
          <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="flex flex-col items-center text-center space-y-4">
              <div className="h-20 w-20 flex items-center justify-center rounded-3xl bg-orange-500/10 text-orange-500 shadow-inner">
                <ShieldCheck className="h-10 w-10" />
              </div>
              <h2 className="text-2xl font-bold text-foreground">Secure your account</h2>
              <p className="text-muted-foreground leading-relaxed">
                Two-factor authentication adds an extra layer of security to your account. In addition to your password, you'll need to enter a code from an authenticator app.
              </p>
            </div>

            <div className="space-y-4">
              <div className="flex gap-4 rounded-2xl border border-border bg-card p-5">
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-secondary text-foreground">
                  <Smartphone className="h-5 w-5" />
                </div>
                <div>
                  <h3 className="font-bold text-foreground">How it works</h3>
                  <p className="text-sm text-muted-foreground mt-1">
                    When you log in, we'll ask for a code generated by your mobile app to verify it's really you.
                  </p>
                </div>
              </div>
            </div>

            <button
              onClick={handleNext}
              className="w-full rounded-full bg-orange-500 py-4 font-bold text-white transition-all hover:bg-orange-600 active:scale-95"
            >
              Get Started
            </button>
          </div>
        )}

        {step === 2 && (
          <div className="space-y-8 animate-in fade-in slide-in-from-right-4 duration-300">
            <div className="space-y-2">
              <h2 className="text-xl font-bold text-foreground">Scan QR Code</h2>
              <p className="text-sm text-muted-foreground">
                Scan this QR code with your authenticator app (like Google Authenticator or Authy).
              </p>
            </div>

            <div className="flex justify-center p-8 rounded-3xl border border-border bg-white transition-transform hover:scale-[1.02]">
              <div className="h-48 w-48 bg-zinc-100 flex items-center justify-center border-2 border-dashed border-zinc-200 rounded-2xl overflow-hidden">
                {/* Mock QR Code */}
                <div className="grid grid-cols-4 gap-1 p-2 bg-black w-32 h-32 opacity-20" />
                <div className="absolute font-mono text-[10px] text-zinc-400 rotate-45 select-none">MOCK QR CODE</div>
              </div>
            </div>

            <div className="space-y-4">
              <p className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Or enter manual key</p>
              <div className="flex items-center justify-between rounded-xl bg-secondary px-4 py-3 font-mono text-sm text-foreground">
                <span>ABCD 1234 EFGH 5678</span>
                <button className="text-xs font-bold text-orange-500 hover:underline">COPY</button>
              </div>
            </div>

            <div className="space-y-4 pt-4">
              <label className="text-sm font-bold text-foreground">Enter 6-digit confirmation code</label>
              <input
                type="text"
                maxLength={6}
                className="w-full tracking-[1em] text-center rounded-xl border border-border bg-card py-4 font-mono text-2xl text-foreground focus:border-orange-500 focus:outline-none"
                placeholder="000000"
              />
            </div>

            <button
              onClick={handleNext}
              className="w-full rounded-full bg-orange-500 py-4 font-bold text-white transition-all hover:bg-orange-600 active:scale-95"
            >
              Enable 2FA
            </button>
          </div>
        )}

        {step === 3 && (
          <div className="flex flex-col items-center text-center space-y-8 py-12 animate-in zoom-in-95 duration-500">
            <div className="relative">
                <div className="absolute inset-0 animate-ping rounded-full bg-green-500 opacity-20" />
                <div className="relative flex h-24 w-24 items-center justify-center rounded-full bg-green-500 text-white shadow-lg shadow-green-500/30">
                  <CheckCircle2 className="h-12 w-12" />
                </div>
            </div>
            
            <div className="space-y-2">
              <h2 className="text-3xl font-bold text-foreground">Verified!</h2>
              <p className="text-muted-foreground">Two-factor authentication is now enabled on your account.</p>
            </div>

            <div className="w-full rounded-2xl bg-secondary/50 p-6 border border-border">
                <h4 className="text-sm font-bold text-foreground inline-flex items-center gap-2 mb-4">
                    <AlertTriangle className="h-4 w-4 text-orange-500" />
                    Save these backup codes
                </h4>
                <div className="grid grid-cols-2 gap-2 text-sm font-mono text-muted-foreground">
                    <div>1234-5678</div>
                    <div>ABCD-EFGH</div>
                    <div>9012-3456</div>
                    <div>IJKL-MNOP</div>
                </div>
            </div>

            <button
              onClick={() => navigate("/settings")}
              className="w-full rounded-full bg-foreground py-4 font-bold text-background transition-all hover:opacity-90 active:scale-95"
            >
              Back to Settings
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default TwoFactorAuth;
